/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.9/samples
 */

tasks.register("hello") {
	doLast {
		println("Hello World!")
	}
}

tasks.register("intro") {
	dependsOn("hello")
	doLast {
		println("Im Learning Gradle")
	}
}

repeat(4) { counter ->
	tasks.register("task$counter") {
		doLast {
			println("Im the task counter")
		}
	}
}
tasks.named("task0") {
	dependsOn("task2", "task3")
}

tasks.named("hello") {
    doFirst {
        println("Hello Venus")
    }
}
tasks.named("hello") {
    doLast {
        println("Hello Mars")
    }
}
tasks.named("hello") {
    doLast {
        println("Hello Jupiter")
    }
}